/** Auto-generated by scripts/convert-product-images.mjs — do not edit manually */
/** Hero carousel uses work photos only (not product catalogue images). */
export const HERO_CAROUSEL_IMAGES: string[] = [
  "/work/work-01.avif",
  "/work/work-02.avif",
  "/work/work-03.avif",
  "/work/work-04.avif",
  "/work/work-06.avif",
  "/work/work-07.avif"
];
